Compile thesis on command line by running:
```/directory/of/files/$ make```

I've added a custom spell checker to the makefile. Spell checking in TexMaker
leaves much to be desired as it flags LaTex commands such as \ref, \cite, etc.

Aspell is used to check spelling instead. To add words to the Aspell dictionary
append to ```inputs/ignore_spelling```. To add LaTex commands to ignore append
to ```inputs/ignore_tex```.

Remove intermediate files generated by compilation:
```/directory/of/files/$ make clean```

Chapters are kept as separate ```.tex``` files in ```chapters/```

Bibliography is styled as in Journal of Fluid Mechanics
